# Generated by Django 4.1.6 on 2023-02-12 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=100)),
                ('taskcompletiondate', models.DateTimeField(default=django.utils.timezone.now)),
                ('taskdescription', models.TextField()),
            ],
        ),
    ]
